export const FETCH_EMPLOYEES_REQUEST = "FETCH_EMPLOYEES_REQUEST";
export const FETCH_EMPLOYEES_SUCCESS = "FETCH_EMPLOYEES_SUCCESS";
export const FETCH_EMPLOYEES_FAILURE = "FETCH_EMPLOYEES_FAILURE";

export const FETCH_EMPLOYEE_ADDRESS_REQUEST = "FETCH_EMPLOYEE_ADDRESS_REQUEST";
export const FETCH_EMPLOYEE_ADDRESS_SUCCESS = "FETCH_EMPLOYEE_ADDRESS_SUCCESS";
export const FETCH_EMPLOYEE_ADDRESS_FAILURE = "FETCH_EMPLOYEE_ADDRESS_FAILURE";
